from __future__ import annotations

import asyncio
from abc import ABC, abstractmethod


class LLMProvider(ABC):
    @abstractmethod
    async def generate(
        self,
        system_prompt: str,
        user_prompt: str,
        temperature: float = 0.1,
        max_tokens: int = 600,
    ) -> str:
        raise NotImplementedError


class MockLLMProvider(LLMProvider):
    async def generate(
        self,
        system_prompt: str,
        user_prompt: str,
        temperature: float = 0.1,
        max_tokens: int = 600,
    ) -> str:
        lowered = f"{system_prompt}\n{user_prompt}".lower()
        if "arabic" in lowered or "العربية" in lowered or "respond only in ar" in lowered:
            return "هذا رد تجريبي من الخدمة. تم تحليل السؤال وتقديم إجابة مختصرة مدعومة بالأدلة المتاحة."
        return "This is a mock policy answer generated by agent-service with deterministic behavior."


class VertexGeminiProvider(LLMProvider):
    def __init__(self, project_id: str, location: str, model: str) -> None:
        self.project_id = project_id
        self.location = location
        self.model = model

    async def generate(
        self,
        system_prompt: str,
        user_prompt: str,
        temperature: float = 0.1,
        max_tokens: int = 600,
    ) -> str:
        return await asyncio.to_thread(
            self._generate_sync,
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            temperature=temperature,
            max_tokens=max_tokens,
        )

    def _generate_sync(self, system_prompt: str, user_prompt: str, temperature: float, max_tokens: int) -> str:
        try:
            import vertexai
            from vertexai.generative_models import GenerativeModel
        except Exception as exc:
            raise RuntimeError(
                "Vertex AI dependencies missing. Install `google-cloud-aiplatform` for vertex mode."
            ) from exc

        if not self.project_id:
            raise RuntimeError("VERTEX_PROJECT_ID is required when `LLM_PROVIDER=vertex`.")

        vertexai.init(project=self.project_id, location=self.location)
        model = GenerativeModel(self.model)
        full_prompt = f"{system_prompt}\n\n{user_prompt}".strip()
        response = model.generate_content(
            full_prompt,
            generation_config={"temperature": temperature, "max_output_tokens": max_tokens},
        )
        return getattr(response, "text", "") or ""
